L26
HyperMe1200/qna pull request #3
Opened 2017-05-24 15:48 UTC by HyperMe1200

2017-05-24 18:41 UTC, vkurennov requested changes

2017-05-24 18:41 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user == @answer.user
1. Лучше сравнивать по id, чтобы не тянуть ассоциацию user у ответа и не делать лишний запрос к базе. Ведь сам объект нам не нужен, надо только сравнить, автор это или нет.
2. Такое сравнение нам понадобится еще не раз, лучше вынести его в метод модели `User#author_of?`

2017-05-24 18:41 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    redirect_to question_path(@answer.question)
Можно просто `redirect_to @answer.question`

2017-05-24 18:41 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy]
Тут проще перечислить, для каких экшенов этот фильтр не нужен. Для этого есть опция `except`

2017-05-24 18:41 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if current_user == @question.user
Замени на вызов `User#author_of?`

2017-05-24 18:41 UTC, vkurennov commented on app/views/questions/_form.html.slim
> += form_for @question do |f|
Тут надо выводить ошибки валидации, не то, что в контроллере через флеш, а именно сами ошибки валидации модели. Одно другое не исключает

2017-05-24 18:41 UTC, vkurennov commented on app/views/questions/show.html.slim
> +- if current_user == @question.user
Замени на вызов `User#author_of?`

2017-05-24 18:41 UTC, vkurennov commented on app/views/questions/show.html.slim
> +    - if current_user == a.user
Замени на вызов `User#author_of?`

2017-05-24 18:41 UTC, vkurennov commented on app/views/questions/show.html.slim
> += form_for [@question, Answer.new] do |f|
Тут тоже надо выводить ошибки валидации

2017-05-24 18:41 UTC, vkurennov commented on spec/acceptance/create_answer_on_question_page_spec.rb
> +  scenario 'Authenticated user creates answer' do
Нужен сценарий на невалидный ответ, все валидации проверять не нужно, это мы делаем в тестах модели, надо просто проверить, что ошибки валидации выводятся на страницу

2017-05-24 18:41 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +    expect(page).to have_content 'Your question successfully created'
Нужно проверить наличие заголовка и тела вопроса

2017-05-24 18:41 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +  scenario 'Authenticated user creates question' do
Также нужен сценарий на невалидный вопрос, проверить, что ошибки валидации выводятся.

2017-05-24 18:41 UTC, vkurennov commented on spec/acceptance/delete_answer_spec.rb
> +feature 'Delete answer', %q{
А где сценарий на успешное удаление ответа? Нужно же все варианты (сценарии) тестировать

2017-05-24 18:41 UTC, vkurennov commented on spec/acceptance/delete_question_spec.rb
> +feature 'Delete question', %q{
И тут тоже нужен сценарий на успешное удаление вопроса

2017-05-24 18:41 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>        it 'saves new answer in database' do
Еще нужен похожий тест, но проверяющий связь с залогиненным юзером

2017-05-24 18:41 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>          expect { post :create, params: { question: attributes_for(:question) } }.to change(Question, :count).by(1)
Тут надо проверить связь с залогиненным юзером

2017-05-24 18:41 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
А тесты на ассоциации?

2017-05-25 09:57 UTC, HyperMe1200 commented on spec/acceptance/delete_answer_spec.rb
> +feature 'Delete answer', %q{
Там есть, ниже. Или не это имеется ввиду?
  scenario 'Delete answer as an author' do
    sign_in(user)
    visit question_path(question)
    click_on 'Delete answer'
    expect(page).to_not have_content (answer.body)
  end

2017-05-25 09:57 UTC, HyperMe1200 commented on spec/acceptance/delete_question_spec.rb
> +feature 'Delete question', %q{
Ниже есть. Или не оно?

2017-05-26 06:49 UTC, vkurennov requested changes

2017-05-26 06:49 UTC, vkurennov commented on app/models/user.rb
> +    id == object.user.id
Вот тут вся идея поломалась. Вызывая object.user.id, ты делаешь доп. запрос к базе (загружаешь юзера) и у него берешь id.  А зачем, если у объекта, раз у него есть связь с user, обязательно должно быть поле user_id, в котором и хранится сам айдишник, и ничего грузить из базы дополнительно, чтобы его получить, не нужно?

2017-05-26 06:49 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  - unless answer.new_record?
Можно еще проверять так: `if answer.persisted?`

2017-05-26 06:49 UTC, vkurennov commented on spec/acceptance/delete_answer_spec.rb
> +feature 'Delete answer', %q{
Точно! Видимо, уже глаз "замылился", я его не так прочитал :-) Сорри.

2017-05-26 06:49 UTC, vkurennov commented on spec/acceptance/delete_answer_spec.rb
> +  scenario 'Delete answer as an non-author' do
Такой же сценарий нужен для незалогиненного юзера

2017-05-26 06:49 UTC, vkurennov commented on spec/acceptance/delete_question_spec.rb
> +feature 'Delete question', %q{
Ага, есть.

2017-05-26 06:49 UTC, vkurennov commented on spec/acceptance/delete_question_spec.rb
> +  scenario 'Delete question as an non-author' do
Такой же сценарий нужен для незалогиненного юзера

2017-05-26 06:49 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { post :create, params: { question: attributes_for(:question) } }.to change(@user.questions, :count).by(1)
Достаточно только этого теста, а предыдущий (где просто Question в change) можно удалить

2017-05-26 06:49 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
А тесты на метод `author_of?` Любой код, который ты пишешь, должен быть покрыть тестами.

2017-05-26 13:13 UTC, vkurennov approved these changes

2017-05-27 17:49 UTC, merged