L29
HyperMe1200/qna pull request #6
Opened 2017-06-15 14:35 UTC by HyperMe1200

2017-06-15 16:17 UTC, iBublik requested changes

2017-06-15 16:17 UTC, iBublik commented on app/models/attachment.rb
> +  belongs_to :attachable, polymorphic: true, optional: true
Разве имеет смысл файл без связанного объекта?

2017-06-15 16:17 UTC, iBublik commented on db/migrate/20170614061537_convert_attachment_to_polymorphic.rb
> +class ConvertAttachmentToPolymorphic < ActiveRecord::Migration[5.1]
Не нужно вносить исправления в таблицы, созданные в рамках этой фичи. Лучше просто откатить миграцию и переделать ее. Так меньше мусора в папке миграций будет

2017-06-15 16:17 UTC, iBublik commented on spec/acceptance/add_files_to_questions_spec.rb
> +    save_and_open_screenshot
Отладку не забывай убирать

2017-06-15 16:25 UTC, HyperMe1200 commented on app/models/attachment.rb
> +  belongs_to :attachable, polymorphic: true, optional: true
Это в примечаниях к заданию было:
"В Rails 5 валидация на ассоциацию belongs_to включена по-умолчанию, но для вложенных объектов и форм ассоциация устанавливается позже, уже после валидации. Из-за этого возникает проблема невалидности объекта при создании. Решение: объявить ассоциацию `belongs_to :attachable` у `Attachment` как `optional: true`."

2017-06-15 16:25 UTC, vkurennov requested changes

2017-06-15 16:25 UTC, vkurennov commented on app/models/answer.rb
> +  accepts_nested_attributes_for :attachments
Добавь опцию `reject_if: :all_blank`, чтобы не было ошибок, если добавляем с пустыми файлами ответ

2017-06-15 16:25 UTC, vkurennov commented on app/models/attachment.rb
> +  belongs_to :attachable, polymorphic: true, optional: true
Да, optional:  true здесь не нужен. Но нужен в другом месте..

2017-06-15 16:25 UTC, vkurennov commented on app/models/question.rb
> +  accepts_nested_attributes_for :attachments
Добавь опцию `reject_if: :all_blank`, чтобы не было ошибок, если добавляем с пустыми файлами вопрос

2017-06-15 16:36 UTC, HyperMe1200 commented on app/models/attachment.rb
> +  belongs_to :attachable, polymorphic: true, optional: true
Не пойму этот момент. Сделал, как в примечании вроде. Посмотрел сейчас у коллег по курсу - у всех есть optional: true тут. Убрал для попробовать - тесты валятся.

2017-06-15 16:39 UTC, HyperMe1200 commented on db/migrate/20170614061537_convert_attachment_to_polymorphic.rb
> +class ConvertAttachmentToPolymorphic < ActiveRecord::Migration[5.1]
Принято, спасибо!

2017-06-16 07:24 UTC, vkurennov commented on app/models/attachment.rb
> +  belongs_to :attachable, polymorphic: true, optional: true
Да, все верно. Это мы ошиблись, сорри. Конечно же, belongs_to нужен здесь, а не на стороне has_many.

2017-06-16 07:29 UTC, HyperMe1200 commented on app/models/attachment.rb
> +  belongs_to :attachable, polymorphic: true, optional: true
За то я конкретно начитался про полиморфные ассоциации :)

2017-06-16 11:29 UTC, vkurennov approved these changes

2017-06-22 05:14 UTC, closed without merging